// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlazhhcdrqllocwvqkuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsYXpoaGNkcnFsbG9jd3Zxa3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjgyNDYsImV4cCI6MjA3MDM0NDI0Nn0.mo6xfKHvZmwXenZZKEPppbXwXNqPrw5hlWn1O8jaTXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});